import 'package:flutter/material.dart';

/* Rectangle Rectangle 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 50.0,
      height: 38.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/38725dce3284d9e2be890bf74a0a923bd9046b06.png",
          color: null,
          fit: BoxFit.cover,
          width: 50.0,
          height: 38.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
