import 'package:flutter/material.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup12Widget1.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedMoleculeheaderWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup16Widget1.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedOWidget1.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/red_socialapp/generatedregistrowidget4/generated/GeneratedGroup17Widget1.dart';

/* Frame registro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistroWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 213, 232, 212),
              Color.fromARGB(0, 213, 232, 212)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 151, 208, 119),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight * 0.053125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.0375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMoleculeheaderWidget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 48.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedGroup16Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedGroup17Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedGroup18Widget1(),
              ),
              Positioned(
                left: 171.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedOWidget1(),
              ),
              Positioned(
                left: 48.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 262.0,
                height: 40.0,
                child: GeneratedGroup12Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 32.0,
                child: GeneratedGroup19Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.6;

                  final double height = constraints.maxHeight * 0.3046875;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.18888888888888888,
                        y: constraints.maxHeight * 0.11875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup6Widget2(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
