import 'package:flutter/material.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedRectangle68Widget9.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedGroup37Widget.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedRectangle67Widget9.dart';
import 'package:flutterapp/red_socialapp/generatedgroup39widget/generated/GeneratedGroup34Widget.dart';

/* Group Group 39
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup39Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 57.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 56.0,
              child: GeneratedRectangle67Widget9(),
            ),
            Positioned(
              left: 286.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedGroup34Widget(),
            ),
            Positioned(
              left: 214.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedGroup35Widget(),
            ),
            Positioned(
              left: 1.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedRectangle68Widget9(),
            ),
            Positioned(
              left: 0.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedGroup36Widget(),
            ),
            Positioned(
              left: 67.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedGroup37Widget(),
            ),
            Positioned(
              left: 142.0,
              top: 1.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 56.0,
              child: GeneratedGroup38Widget(),
            )
          ]),
    ));
  }
}
