import 'package:flutter/material.dart';

/* Rectangle image 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 40.0,
      height: 35.407405853271484,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/c7907f9f3a5525c143cdb5c8606391118d658da8.png",
          color: null,
          fit: BoxFit.cover,
          width: 40.0,
          height: 35.407405853271484,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
