import 'package:flutter/material.dart';

/* Rectangle image 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 45.0,
      height: 47.47881317138672,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/36e3902bc7f7c2fd9505ec22ae0a5a34cf0fa9a9.png",
          color: null,
          fit: BoxFit.cover,
          width: 45.0,
          height: 47.47881317138672,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
